SELECT GETDATE();

SELECT DATEADD(YEAR,7,GETDATE());

--DATE DIFF--

SELECT DATEDIFF(DAY,'2026-7-31',GETDATE());

--DATEPART--

SELECT DATEPART(YEAR,GETDATE());
SELECT DATEPART(MONTH,GETDATE());
SELECT DATEPART(DAY,GETDATE());

SELECT DAY(GETDATE());

--FORMAT FOR DATE
SELECT FORMAT(GETDATE(),'MM/dd/yyyy');